#!/bin/sh
#
#  Configure the new image to be a minimal image, by removing
# packages I don't care about - and installing new ones I prefer.
#
# Steve
# --
# http://www.steve.org.uk/
#


prefix=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    echo "Installation problem"
fi




#
#  Install some new packages - do this first to avoid dependency errors.
#
installCentOS4Package ${prefix} kernel-xen
installCentOS4Package ${prefix} less
installCentOS4Package ${prefix} screen
installCentOS4Package ${prefix} sudo
installCentOS4Package ${prefix} vim


