#!/bin/sh
#
#  Configure the new image to be a minimal image, by removing
# packages I don't care about - and installing new ones I prefer.
#
# Steve
# --
# http://www.steve.org.uk/
#


prefix=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    echo "Installation problem"
fi




#
#  Install some new packages - do this first to avoid dependency errors.
#
removeDebianPackage ${prefix} grub 
removeDebianPackage ${prefix} grub-common 
removeDebianPackage ${prefix} libfreetype6 
removeDebianPackage ${prefix} libfuse2 
removeDebianPackage ${prefix} os-prober

updateDebianPackages ${prefix}
upgradeDebianPackages ${prefix}
installDebianPackage ${prefix} linux-image-server
installDebianPackage ${prefix} syslog-ng 
installDebianPackage ${prefix} deborphan
installDebianPackage ${prefix} less
installDebianPackage ${prefix} screen
installDebianPackage ${prefix} sudo
installDebianPackage ${prefix} vim
installDebianPackage ${prefix} iptables

